Fix fetch.

diff --git a/poker_bin b/poker_bin
--- a/poker_bin
+++ b/poker_bin
@@ -1,5 +1,5 @@
 #!/bin/bash
-# vim: set foldmethod=marker shiftwidth=2 st=2 ts=2:
+# vim: set foldmethod=marker shiftwidth=2 st=2 ts=2 expandtab:
 
 POKER_VERSION="0.1"
 POKER_HOME=$HOME/.poker/
@@ -76,7 +76,7 @@ cmd_list() {
     pkg_name="$1"
     echo "Avaliable versions for package '$pkg_name':"
     GIT_DIR="$(repo_path)" git ls-remote -t origin "$pkg_name/*" | sed "s/^.\+\srefs\/tags\/$pkg_name\//  /"
-		# TODO(timgreen): legacy git (1.7) doesn't support --exit-code
+    # TODO(timgreen): legacy git (1.7) doesn't support --exit-code
   else
     cmd_help list
     exit 1
@@ -102,12 +102,15 @@ cmd_fetch() {
 
   pkg_name="$1"
   version="$2"
-  output="$3"
+  output="$(readlink -m $3)"
 
-  GIT_DIR="$(repo_path)" git fetch origin "refs/tags/$pkg_name/$version" &> /dev/null
+  cd "$(repo_path)"
+  git fetch origin "refs/tags/$pkg_name/$version" &> /dev/null
   (( $? != 0 )) && { echo "Can not found package $pkg_name with version $version"; exit 1; }
 
-  GIT_DIR="$(repo_path)" git archive --format=tar -o "$output" "$pkg_name/$version"
+  rm -f "$output"
+  git archive --format=tar -o "$output" "$pkg_name/$version"
+  [ -r "$output" ] || { echo "Fetch failed"; exit 1; }
 }
 
 cmd_push() {
@@ -135,7 +138,7 @@ cmd_push() {
   git fetch repo $pkg_name || git fetch repo master
   git reset --hard FETCH_HEAD
   git rm -fr *
-  cp -r "$pkg_dir/"* .
+  [ -r "$pkg_dir" ] && cp -r "$pkg_dir/"* . || { echo "$pkg_dir not found"; exit 2; }
   git add *
   git commit --allow-empty -m "$pkg_name:$version"
   git tag "$pkg_name/$version"
