Impl command fetch.

diff --git a/poker b/poker
--- a/poker
+++ b/poker
@@ -63,14 +63,14 @@ cmd_list() {
 
   if (( $# == 0 )); then
     echo "Avaliable packages:"
-    git ls-remote -h $(repo_path) | sed 's/^.\+\srefs\/heads\//  /' |  \
+    GIT_DIR="$(repo_path)" git ls-remote -h origin | sed 's/^.\+\srefs\/heads\//  /' |  \
         grep -v '\bmaster$'
 
     exit 0
   elif (( $# == 1)); then
     pkg_name="$1"
     echo "Avaliable versions for package '$pkg_name':"
-    git ls-remote --exit-code -t $(repo_path) "$pkg_name/*" | sed "s/^.\+\srefs\/tags\/$pkg_name\//  /"
+    GIT_DIR="$(repo_path)" git ls-remote --exit-code -t origin "$pkg_name/*" | sed "s/^.\+\srefs\/tags\/$pkg_name\//  /"
     # TODO:
   else
     cmd_help list
@@ -82,9 +82,27 @@ cmd_sync() {
   read_config
   prepare_repo
 
-  cd "$(repo_path)"
-  git fetch --progress
-  git fetch -t --progress
+  GIT_DIR="$(repo_path)" git fetch --progress
+  GIT_DIR="$(repo_path)" git fetch -t --progress
+}
+
+cmd_fetch() {
+  read_config
+  prepare_repo
+
+  if (( $# != 3 )); then
+    cmd_help fetch
+    exit 1
+  fi
+
+  pkg_name="$1"
+  version="$2"
+  output="$3"
+
+  GIT_DIR="$(repo_path)" git fetch origin "$pkg_name/$version" &> /dev/null
+  (( $? != 0 )) && { echo "Can not found package $pkg_name with version $version"; exit 1; }
+
+  GIT_DIR="$(repo_path)" git archive --format=tar -o "$output" "$pkg_name/$version"
 }
 
 ## }}} Commands
@@ -95,6 +113,7 @@ shift
 case $command in
   list)     cmd_list "$@";;
   sync)     cmd_sync;;
+  fetch)    cmd_fetch "$@";;
   version)  cmd_version;;
   help)     cmd_help;;
   *)        cmd_help
